language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: required
services:
  - docker
notifications:
  on_success:
    - change
  on_failure:
    - change
env:
  global:
    - SC_BUILD_DIR=`pwd`
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.embedpostgresql
    - $HOME/.embedmysql
addons:
  apt:
    packages:
      - graphviz
script:
  - echo $SC_BUILD_DIR
  - cd "./schemacrawler-database-plugins-parent"
  - mvn -Dcomplete clean package jacoco:report-aggregate coveralls:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - cd $SC_BUILD_DIR
  - git fetch --tags
